defaults:
    - override hydra/launcher: submitit_slurm

# environment
task: dog-run
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 1_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: tdmpc2
wandb_entity: eop
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: false
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

hydra:
  job:
    chdir: True
    env_set:
      MUJOCO_GL: glfw
  launcher:
    timeout_min: 5750
    max_num_timeout: 10
    submitit_folder: /h/eop/submitit
    qos: scavenger
    gres: gpu:1
    partition: rtx6000,a40,t4v1,t4v2
    mem_gb: 64
    cpus_per_task: 16
    setup:
      - "source ~/.bashrc"
      - "module load pytorch2.1-cuda11.8-python3.9; export MUJOCO_PY_BYPASS_LOCK=True; export LD_LIBRARY_PATH=/pkgs/cudnn-8.8/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH=/pkgs/cuda-11.8/extras/CUPTI/lib64/:$LD_LIBRARY_PATH; export MUJOCO_GL=egl; cd ~/rl/tdmpc2_fork/tdmpc2; conda activate tdmpc2"
      - "hostname"
      - "nvidia-smi"
